Run in CI until failure

diff --git a/.github/workflows/integration-tests.yml b/.github/workflows/integration-tests.yml
--- a/.github/workflows/integration-tests.yml
+++ b/.github/workflows/integration-tests.yml
@@ -71,7 +71,16 @@ jobs:
       - name: Build
         run: cargo build --features "service_debug data-consistency-check" --locked
       - name: Run integration tests - multiple peers - pytest
-        run: poetry -C tests run pytest tests/consensus_tests --durations=10 -k "test_failed_snapshot_recovery"
+        run: |
+          set +e # ignore errors
+          counter=0
+          while poetry -C tests run pytest tests/consensus_tests --durations=10 -k "test_failed_snapshot_recovery"; do
+              counter=$((counter + 1))
+              echo "==========Test passed $counter times. Running again...========="
+          done
+
+          echo "Test failed. Exiting."
+          exit 1
         timeout-minutes: 60
       - name: upload logs
         uses: actions/upload-artifact@v4
